# main ES cluster
client:
    extends:
      file: common.yml
      service: client
    links:
      - marvel
    command: ./elasticsearch --node.client true --marvel.agent.exporter.es.hosts "http://marvel_export:password@marvel:9200"

data2:
    extends:
      file: common.yml
      service: data
    links:
      - marvel
    command: ./elasticsearch --marvel.agent.exporter.es.hosts "http://marvel_export:password@marvel:9200"

data1:
    extends:
      file: common.yml
      service: data
    links:
      - marvel
    command: ./elasticsearch --marvel.agent.exporter.es.hosts "http://marvel_export:password@marvel:9200"

# marvel ES cluster
marvel:
    extends:
      file: common.yml
      service: data
    ports:
        - 9201:9200
    command: ./elasticsearch --marvel.agent.enabled false --cluster.name marvel
    
    
kibana:
    image: kibana:latest
    volumes:
        - ./config:/config
    ports:
        - 5601:5601
    links:
        - marvel
    command: /opt/kibana/bin/kibana --config /config/kibana-jmeter.yml



# jMeter servers
jmeter1:
    build: jmeter
    links:
      - client

jmeter2:
    build: jmeter
    links:
      - client

jmeter_client:
    build: jmeter
    volumes:
        - ./load-test:/load-test
    ports:
      - 4445
    links:
      - marvel
      - jmeter1
      - jmeter2
    command: sh -c "sleep 20; ./jmeter -n -t /load-test/test1.jmx -R jmeter1,jmeter2"

