client:
    extends:
      file: common.yml
      service: client
    ports:
        - 9200:9200
    links:
      - marvel


#main ES cluster
data2:
    extends:
      file: common.yml
      service: data
    links:
      - marvel
    ports:
      - 9202:9200
    command: ./elasticsearch --network.host _non_loopback_

data1:
    extends:
      file: common.yml
      service: data
    links:
      - marvel
    ports:
      - 9201:9200
    command: ./elasticsearch --network.host _non_loopback_


# marvel ES cluster
marvel:
    extends:
      file: common.yml
      service: data
    hostname: marvel
    ports:
      - 9203:9200
      - 9300:9300
    command: ./elasticsearch --marvel.agent.interval -1  --cluster.name marvel --network.host _non_loopback_


kibana_client:
    build: kibana
    volumes:
        - ./data:/data
        - ./config:/config
        - ./logs:/logs
    ports:
      - 5601:5601
    links:
        - client
    command: /opt/kibana/bin/kibana --config /config/kibana.yml


kibana_marvel:
    build: kibana
    volumes:
        - ./data:/data
        - ./config:/config
        - ./logs:/logs
    ports:
      - 5602:5601
    links:
        - marvel
    command: /opt/kibana/bin/kibana --config /config/kibana-marvel.yml


# jMeter servers
jmeter1:
    build: jmeter
    hostname: jmeter1
    volumes:
      - ./load-test:/load-test
    links:
      - client
      - marvel
    command: sh -c "./jmeter -s -Djava.rmi.server.hostname=jmeter1"

jmeter2:
    build: jmeter
    hostname: jmeter2
    volumes:
      - ./load-test:/load-test
    links:
      - client
      - marvel
    command: sh -c "./jmeter -s -Djava.rmi.server.hostname=jmeter2"


jmeter_client_1:
    build: jmeter
    volumes:
      - ./load-test:/load-test
    ports:
      - 4445
    links:
      - jmeter1
      - jmeter2
      - marvel
      - client
    command: sh -c "sleep 120; ./jmeter -n -t /load-test/run_queries_and_bulk_index.jmx -GinputFiles=21 -GindexName=apachelogs -GtypeName=logs -GqueryThroughPut=20.0 -GindexThroughPut=10.0 -JtestRunId=T1812.2 -R jmeter1,jmeter2"


# jmeter_client_2:
#     build: jmeter
#     volumes:
#       - ./load-test:/load-test
#     ports:
#       - 4445
#     links:
#       - marvel
#       - client
#     command: sh -c "sleep 120; ./jmeter -n -t /load-test/cluster_health.jmx -JindexName=apachelogs -JtypeName=logs -JtestRunId=T1812.1"



