# main ES cluster
client:
    extends:
      file: common.yml
      service: client
    ports:
        - 9300:9300
    links:
      - marvel
    command: ./elasticsearch --node.client true --marvel.agent.exporter.es.hosts "http://marvel_export:password@marvel:9200"

data2:
    extends:
      file: common.yml
      service: data
    links:
      - marvel
    command: ./elasticsearch --marvel.agent.exporter.es.hosts "http://marvel_export:password@marvel:9200"

data1:
    extends:
      file: common.yml
      service: data
    links:
      - marvel
    command: ./elasticsearch --marvel.agent.exporter.es.hosts "http://marvel_export:password@marvel:9200"

# marvel ES cluster
marvel:
    extends:
      file: common.yml
      service: data
    ports:
        - 9201:9200
    command: ./elasticsearch --marvel.agent.enabled false --cluster.name marvel


# jMeter instances
jmeter1:
    build: jmeter
    volumes:
        - ./load-test:/load-test
    ports:
      - 1099:1099

# jmeter2:
#     image: jmeter
#     environment:
#       - RMI_LOCALPORT=40001
#       - SERVER_PORT 30001
#     ports:
#       - 30001:30001
#     net: "host"
#     dns:
#       - 8.8.8.8
#     command: apache-jmeter-2.13/bin/jmeter -s -j jmeter-server.log -Dserver.rmi.localhostname=192.168.99.100 -Dserver.rmi.localport=40001 -Dserver_port=30001 -Djava.rmi.server.hostname=192.168.99.100

