cluster.name: elk_poc_cluster

path:
  data: /data/
  work: /data/work


shield:
  authc:
    realms:
      default:
        type: esusers
        order: 0

# uncomment to allow anonymous access:
#  anonymous:
#    username: es_admin
#    roles: admin

script:
  inline: on
  indexed: on

marvel.agent.exporter.es.hosts: [ "http://marvel_export:password@client:9200" ]

http:
  enabled: false
  cors.enabled: true
