cluster.name: elk_poc_cluster

discovery.zen.ping.multicast.enabled: true



path:
  data: /data/
  work: /data/work
  logs: /logs


shield:
  authc:
    realms:
      default:
        type: esusers
        order: 0

# uncomment to allow anonymous access:
#  anonymous:
#    username: es_admin
#    roles: admin

script:
  inline: on
  indexed: on


marvel.agent.exporters:
  id1:
    type: http
    host: ["http://marvel:9200"]
    auth:
      username: es_admin
      password: password

http:
  cors.enabled: true
