
# The Elasticsearch instance to use for all your queries.
elasticsearch_url: "http://marvel:9200"

# If your Elasticsearch is protected with basic auth, this is the user credentials
# used by the Kibana server to perform maintence on the kibana_index at statup. Your Kibana
# users will still need to authenticate with Elasticsearch (which is proxied thorugh
# the Kibana server)
kibana_elasticsearch_username: "kibana4-server"
kibana_elasticsearch_password: "password"

